app/student/__init__.py
from flask import Blueprint

student_bp = Blueprint('student', __name__, template_folder='templates')

from . import views

app/student/views.py
import os

import pandas
import pandas as pd
import qrcode
from flask import render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from models.attendance import Attendance
from models.session import Session
from models.student import Student
from . import student_bp
from .form import AttendanceForm
from .. import db


@student_bp.route("/list")
@login_required
def list():
    return render_template("student/list.html")


@student_bp.route("/student/<int:student_id>")
@login_required
def post(student_id):
    return render_template("student/details.html", student_id=student_id)


@student_bp.route("/create", methods=["GET", "POST"])
@login_required
def register():
    return render_template("student/create.html")


@student_bp.route("/album", methods=["GET"])
@login_required
def album_list():
    #students = Student.query.filter((Student.employment_status != 'Employed')).order_by(Student.id).all()  #db.session.execute(db.select(Student).order_by(Student.id)).scalars().all()
    students = Student.query.order_by(Student.id).all()
    return render_template(
        "student/card.html", students=students, title="Student Album"
    )


@student_bp.route("/wb-album-for-male", methods=["GET"])
@login_required
def wb_album():
    #students = Student.query.filter((Student.employment_status != 'Employed') & (Student.gender=='Male') & (Student.disabled =='no')).order_by(Student.id).all()  #db.session.execute(db.select(Student).order_by(Student.id)).scalars().all()
    students = Student.query.filter(
        (Student.gender == 'Male') & (Student.disabled == 'no')).order_by(
        Student.id).all()
    return render_template(
        "student/foralbum.html", students=students, title="Student Album"
    )


@student_bp.route("/wb-album-for-female", methods=["GET"])
@login_required
def wb_album_female():
    #students = Student.query.filter((Student.employment_status != 'Employed') & (Student.gender=='Female')).order_by(Student.id).all()  #db.session.execute(db.select(Student).order_by(Student.id)).scalars().all()
    students = Student.query.filter((Student.gender == 'Female')).order_by(
        Student.id).all()
    return render_template(
        "student/foralbum.html", students=students, title="Student Album"
    )


@student_bp.route("/wb-album-for-disabled", methods=["GET"])
@login_required
def wb_album_disabled():
    #students = Student.query.filter((Student.employment_status != 'Employed') & (Student.disabled=='yes')).order_by(Student.id).all()  #db.session.execute(db.select(Student).order_by(Student.id)).scalars().all()
    students = Student.query.filter((Student.disabled == 'yes')).order_by(
        Student.id).all()
    return render_template(
        "student/foralbum.html", students=students, title="Student Album"
    )


@student_bp.route("/attendance", methods=["GET"])
@login_required
def attendance_list():
    attendances = Attendance.query.all()

    return render_template("attendance/index.html", attendances=attendances)


@student_bp.route("/attendance/upload", methods=["GET", "POST"])
@login_required
def attendance_upload():
    form = AttendanceForm()
    if form.validate_on_submit():
        print('here')
        try:
            file = form.upload.data
            print(file)
            if file.filename.endswith('.xlsx'):
                df = pd.read_excel(file)
            elif file.filename.endswith('.csv'):
                df = pd.read_csv(file)
            else:
                raise ValueError("Invalid file format. Supported formats: .xlsx, .csv")

            for _, row in df.iterrows():
                student = Student.query.with_entities(Student.id).filter_by(phone_number=row[0]).first()
                attendance = Attendance(
                    student_id=student.id,
                    status=True if row[1] == '1' else False,
                    taken_by=current_user.id
                )
                db.session.add(attendance)
                db.session.commit()

                flash('Your account has been created! You are now able to log in.', 'success')
                return redirect(url_for('attendance_list'))

        except Exception as e:
            return render_template('attendance/create.html', str(e))

    return render_template('attendance/create.html', form=form)


@student_bp.route('/generate-card', methods=['GET', 'POST'])
def generate_card():
    global qrcode_url
    if request.method == 'POST':
        phone_number = request.form.get('phone_number')
        student = Student.query.filter_by(phone_number=phone_number).first()

        if student:
            qr = qrcode.make(student.phone_number)
            qr_img_path = os.path.join('app/static', 'qrcodes', f'{student.phone_number}.png')
            qr.save(qr_img_path, format='PNG')

            filename = f'static/qrcodes/{student.phone_number}.png'
            qrcode_url = request.host_url + filename
            student_session = Session.query.filter_by(id=student.stud_session).first()

            if student_session:
                details = {
                    'student': student,
                    'session': student_session.duration,
                    'qrcode_url': qrcode_url,
                    'error': None
                }

                return render_template('student/generated_card.html', **details)

            else:
                details = {
                    'student': None,
                    'error': "You're not given admission. Please contact Administrator"
                }
                return render_template('student/generated_card.html', **details)

        details = {
            'student': None,
            'error': "Learner with the provided details is not found"
        }
        return render_template('student/generated_card.html', **details)

    return render_template('student/generated_card.html')


@student_bp.route('/get-card/', methods=['GET'])
def get_card():
    fullname = request.args.get('fullname', None)
    session = request.args.get('session', None)
    headshot = request.args.get('headshot', None)
    learnerId = request.args.get('learnerId', None)
    qrcode_url = request.args.get('qrcode_url', None)
    course = request.args.get('course', None)

    return render_template('idcard.html', headshot=headshot, fullname=fullname, qrcode_url=qrcode_url, course=course, learnerId=learnerId, session=session)

app/student/templates/attendance/create.html
{% extends 'base.html' %}

{% block title %} Student Attendance {% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" action="{{ url_for('student.attendance_upload') }}">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.upload.label }}
             {{ form.upload(class="form-control form-control-lg border-left-0", placeholder="Upload attendance") }}
                    {% for error in form.upload.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
        </div>
        <div class="form-group">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
{% endblock %}

app/student/templates/attendance/index.html
{% extends 'base.html' %}

{% block title %} Student Attendance {% endblock %}

{% block content %}
    <a href="{{ url_for('student.attendance_upload') }}">Post Attendance</a>
{% endblock %}

app/student/templates/student/card.html
{% if current_user.role == 'admin' or current_user.username == 'worldbank' %}
    {% extends 'base.html' %}
{% else %}
    {% extends 'guest_base.html' %}
{% endif %}


{% block title %} Student Album {% endblock %}

{% block content %}
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <div class="container-fluid mt-2" id="card">
        <div class="{% if current_user.role == 'admin' or current_user.username == 'worldbank' %} albumcard {% else %} custom-card {% endif %} mt-2" style="--bs-columns: {% if current_user.role == 'admin' %} 4 {% else %} 5 {% endif %};">
            {% if students %}
                {% for student in students %}
                    <div class="grid card h-100 m-1" style="width: 18rem;">
                        {% if student.headshot %}
                            <img src="{{ student.headshot }}" class="card-img-top h-50" alt="{{ student.first_name }}">
                        {% else %}
                            <img src="{{ url_for('static', filename='nvit-logo.png') }}" class="card-img-top h-50" alt="{{ student.first_name }}">
                        {% endif %}
                        <div class="card-body px-2">
                            <div class="row no-gutters mb-1">
                                <div class="col-4 card-text" style="font-size: 12px; font-weight: bold;">Learner's Name:&nbsp;</div>
                                <div class="col-8"><h6 class="card-text" style="font-size: 12px;">{{ student.full_name()|upper }}</h6></div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-4 card-text" style="font-size: 12px; font-weight: bold;">Learner ID:&nbsp;</div>
                                <div class="col-8 card-text" style="font-size: 12px;">{{ student.student_no }}</div>
                            </div>
                            <hr class="my-1" />
                            <div class="row no-gutters my-1">
                                <div class="col-4 card-text" style="font-size: 12px; font-weight: bold;">Course of Study:&nbsp;</div>
                                <div class="col-8 card-text" style="font-size: 12px;">{{ student.course_of_study }}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-4 card-text" style="font-size: 12px; font-weight: bold;">Gender:&nbsp;</div>
                                <div class="col-8 card-text" style="font-size: 12px;">{{ student.gender|capitalize }}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-4 card-text" style="font-size: 12px; font-weight: bold;">Phone:&nbsp;</div>
                                <div class="col-8 card-text" style="font-size: 12px;">{{ student.phone_number|capitalize }}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-4 card-text" style="font-size: 12px; font-weight: bold;">Email:&nbsp;</div>
                                <div class="col-8 card-text" style="font-size: 12px;">{{ student.email}}</div>
                            </div>
                            <hr class="my-1" />
                            <div class="d-flex justify-content-between align-center">
                                <span class="card-text" style="font-size: 12px"><b>State:</b>&nbsp;{{ student.state_of_origin|capitalize }}</span>
                                <span class="card-text" style="font-size: 12px"><b>LGA:</b>&nbsp;{{ student.lga_of_origin|capitalize }}</span>
                            </div>
                            <div class="my-1">
                                {% if student.means_of_id_no %}
                                    <span class="card-text" style="font-size: 12px;"><b>NIN:</b> {{ student.means_of_id_no }}</span>
                                {% else %}
                                    <span class="card-text" style="font-size: 12px;">Pending</span>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-sm-12 d-flex justify-content-center align-center">
                    <h5>No Record found!</h5>
                </div>
            {% endif %}
        </div>
    </div>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: "Inter", sans-serif;
        }
        .formbold-main-wrapper {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 48px;
        }

        .formbold-form-wrapper {
            margin: 0 auto;
            max-width: 550px;
            width: 100%;
            background: white;
        }

        .formbold-steps {
            padding-bottom: 18px;
            margin-bottom: 35px;
            border-bottom: 1px solid #DDE3EC;
        }
        .formbold-steps ul {
            padding: 0;
            margin: 0;
            list-style: none;
            display: flex;
            gap: 40px;
        }
        .formbold-steps li {
            display: flex;
            align-items: center;
            gap: 14px;
            font-weight: 500;
            font-size: 16px;
            line-height: 24px;
            color: #536387;
        }
        .formbold-steps li span {
            display: flex;
            align-items: center;
            justify-content: center;
            background: #DDE3EC;
            border-radius: 50%;
            width: 36px;
            height: 36px;
            font-weight: 500;
            font-size: 16px;
            line-height: 24px;
            color: #536387;
        }
        .formbold-steps li.active {
            color: #07074D;;
        }
        .formbold-steps li.active span {
            background: #6A64F1;
            color: #FFFFFF;
        }

        .formbold-input-flex {
            display: flex;
            gap: 20px;
            margin-bottom: 22px;
        }
        .formbold-input-flex > div {
            width: 50%;
        }
        .formbold-form-input {
            width: 100%;
            padding: 13px 22px;
            border-radius: 5px;
            border: 1px solid #DDE3EC;
            background: #FFFFFF;
            font-weight: 500;
            font-size: 16px;
            color: #536387;
            outline: none;
            resize: none;
        }
        .formbold-form-input:focus {
            border-color: #6a64f1;
            box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
        }
        .formbold-form-label {
            color: #07074D;
            font-weight: 500;
            font-size: 14px;
            line-height: 24px;
            display: block;
            margin-bottom: 10px;
        }

        .formbold-form-confirm {
            border-bottom: 1px solid #DDE3EC;
            padding-bottom: 35px;
        }
        .formbold-form-confirm p {
            font-size: 16px;
            line-height: 24px;
            color: #536387;
            margin-bottom: 22px;
            width: 75%;
        }
        .formbold-form-confirm > div {
            display: flex;
            gap: 15px;
        }

        .formbold-confirm-btn {
            display: flex;
            align-items: center;
            gap: 10px;
            background: #FFFFFF;
            border: 0.5px solid #DDE3EC;
            border-radius: 5px;
            font-size: 16px;
            line-height: 24px;
            color: #536387;
            cursor: pointer;
            padding: 10px 20px;
            transition: all .3s ease-in-out;
        }
        .formbold-confirm-btn {
            box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.12);
        }
        .formbold-confirm-btn.active {
            background: #6A64F1;
            color: #FFFFFF;
        }

        .formbold-form-step-1,
        .formbold-form-step-2,
        .formbold-form-step-3 {
            display: none;
        }
        .formbold-form-step-1.active,
        .formbold-form-step-2.active,
        .formbold-form-step-3.active {
            display: block;
        }

        .formbold-form-btn-wrapper {
            display: flex;
            align-items: center;
            justify-content: flex-end;
            gap: 25px;
            margin-top: 25px;
        }
        .formbold-back-btn {
            cursor: pointer;
            background: #FFFFFF;
            border: none;
            color: #07074D;
            font-weight: 500;
            font-size: 16px;
            line-height: 24px;
            display: none;
        }
        .formbold-back-btn.active {
            display: block;
        }
        .formbold-btn {
            display: flex;
            align-items: center;
            gap: 5px;
            font-size: 16px;
            border-radius: 5px;
            padding: 10px 25px;
            border: none;
            font-weight: 500;
            background-color: #6A64F1;
            color: white;
            cursor: pointer;
        }
        .formbold-btn:hover {
            box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
        }
    </style>
    <script>
        const stepMenuOne = document.querySelector('.formbold-step-menu1')
        const stepMenuTwo = document.querySelector('.formbold-step-menu2')
        const stepMenuThree = document.querySelector('.formbold-step-menu3')

        const stepOne = document.querySelector('.formbold-form-step-1')
        const stepTwo = document.querySelector('.formbold-form-step-2')
        const stepThree = document.querySelector('.formbold-form-step-3')

        const formSubmitBtn = document.querySelector('.formbold-btn')
        const formBackBtn = document.querySelector('.formbold-back-btn')

        formSubmitBtn.addEventListener("click", function(event){
            event.preventDefault()
            if(stepMenuOne.className == 'formbold-step-menu1 active') {
                event.preventDefault()

                stepMenuOne.classList.remove('active')
                stepMenuTwo.classList.add('active')

                stepOne.classList.remove('active')
                stepTwo.classList.add('active')

                formBackBtn.classList.add('active')
                formBackBtn.addEventListener("click", function (event) {
                event.preventDefault()

                stepMenuOne.classList.add('active')
                stepMenuTwo.classList.remove('active')

                stepOne.classList.add('active')
                stepTwo.classList.remove('active')

                formBackBtn.classList.remove('active')

                })

            } else if(stepMenuTwo.className == 'formbold-step-menu2 active') {
                event.preventDefault()

                stepMenuTwo.classList.remove('active')
                stepMenuThree.classList.add('active')

                stepTwo.classList.remove('active')
                stepThree.classList.add('active')

                formBackBtn.classList.remove('active')
                formSubmitBtn.textContent = 'Submit'
            } else if(stepMenuThree.className == 'formbold-step-menu3 active') {
                document.querySelector('form').submit()
            }
        })
    </script>
{% endblock %}

app/student/templates/student/detail.html
{% if current_user.role == 'admin' %}
    {% extends 'base.html' %}
{% else %}
    {% extends 'guest_base.html' %}
{% endif %}


{% block title %} Student Details {% endblock %}

{% block content %}
<div class="container-fluid mt-2">
    <div class="row">
        <div class="card d-flex">
            <div class="row py-3 d-flex align-center justify-content-center">
                <div class="col-6">
                    <h5>{{ student.first_name }} {{ student.middle_name }} {{ student.last_name }}</h5>
                </div>
                <div class="d-flex col-6 float-end right justify-content-end gap-2">
                    <a href="/update">
                        <button type="button" class="btn btn-warning text-white">Edit</button>
                    </a>
                    <a href="/delete">
                        <button type="button" class="btn btn-danger">Delete</button>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6">
            <div class="card">
                  <div class="card-body">
                    This is some text within a card body.
                  </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card mb-2">
                  <div class="card-header">
                      <h5>Document Upload</h5>
                  </div>
                  <div class="card-body">
                    This is some text within a card body.
                  </div>
            </div>
            <div class="card">
                  <div class="card-header">
                      <h5>Document Viewer</h5>
                  </div>
                  <div class="card-body">
                    This is some text within a card body.
                  </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/student/templates/student/foralbum.html
{% if current_user.role == 'admin' or current_user.username == 'worldbank' %}
    {% extends 'base.html' %}
{% else %}
    {% extends 'guest_base.html' %}
{% endif %}


{% block title %} Student Album {% endblock %}

{% block content %}
    <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    </head>
    <div class="container-fluid mt-2" id="card">
        <div class="{% if current_user.role == 'admin' or current_user.username == 'worldbank' %} albumcard {% else %} custom-card {% endif %} mt-2" style="--bs-columns: {% if current_user.role == 'admin' %} 4 {% else %} 5 {% endif %};">
            {% if students %}
                {% for index, student in enumerate(students) %}
                    <div class="grid card h-100 m-1" style="width: 18rem;">
                        {% if student.headshot %}
                            <img src="{{ student.headshot }}" class="card-img-top h-50" alt="{{ student.first_name }}">
                        {% else %}
                            <img src="{{ url_for('static', filename='nvit-logo.png') }}" class="card-img-top h-50" alt="{{ student.first_name }}">
                        {% endif %}
                        <div class="card-body px-2">
                            <div class="row no-gutters mb-1">
                                <div class="col-12"><h6 class="card-text" style="font-size: 12px;">Name:&nbsp;{{ student.full_name()|upper }}</h6></div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">Course:&nbsp;{{ student.student_course() }}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">Phone:&nbsp;{{ student.phone_number }}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">Email:&nbsp;{{ student.email}}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">LGA:&nbsp;{{ student.lga_of_origin|capitalize}}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">State:&nbsp;{{ student.state_of_origin|capitalize}}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">NIN:&nbsp;{{ student.means_of_id_no}}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">Disability (Don't copy):&nbsp;{{ student.disabled|capitalize}}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">S/No:&nbsp;{{ index + 1}}</div>
                            </div>
                            <div class="row no-gutters my-1">
                                <div class="col-12 card-text" style="font-size: 12px;">Gender:&nbsp;{{ student.gender|capitalize }}</div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="col-sm-12 d-flex justify-content-center align-center">
                    <h5>No Record found!</h5>
                </div>
            {% endif %}
        </div>
    </div>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: "Inter", sans-serif;
        }
        .formbold-main-wrapper {
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 48px;
        }

        .formbold-form-wrapper {
            margin: 0 auto;
            max-width: 550px;
            width: 100%;
            background: white;
        }

        .formbold-steps {
            padding-bottom: 18px;
            margin-bottom: 35px;
            border-bottom: 1px solid #DDE3EC;
        }
        .formbold-steps ul {
            padding: 0;
            margin: 0;
            list-style: none;
            display: flex;
            gap: 40px;
        }
        .formbold-steps li {
            display: flex;
            align-items: center;
            gap: 14px;
            font-weight: 500;
            font-size: 16px;
            line-height: 24px;
            color: #536387;
        }
        .formbold-steps li span {
            display: flex;
            align-items: center;
            justify-content: center;
            background: #DDE3EC;
            border-radius: 50%;
            width: 36px;
            height: 36px;
            font-weight: 500;
            font-size: 16px;
            line-height: 24px;
            color: #536387;
        }
        .formbold-steps li.active {
            color: #07074D;;
        }
        .formbold-steps li.active span {
            background: #6A64F1;
            color: #FFFFFF;
        }

        .formbold-input-flex {
            display: flex;
            gap: 20px;
            margin-bottom: 22px;
        }
        .formbold-input-flex > div {
            width: 50%;
        }
        .formbold-form-input {
            width: 100%;
            padding: 13px 22px;
            border-radius: 5px;
            border: 1px solid #DDE3EC;
            background: #FFFFFF;
            font-weight: 500;
            font-size: 16px;
            color: #536387;
            outline: none;
            resize: none;
        }
        .formbold-form-input:focus {
            border-color: #6a64f1;
            box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
        }
        .formbold-form-label {
            color: #07074D;
            font-weight: 500;
            font-size: 14px;
            line-height: 24px;
            display: block;
            margin-bottom: 10px;
        }

        .formbold-form-confirm {
            border-bottom: 1px solid #DDE3EC;
            padding-bottom: 35px;
        }
        .formbold-form-confirm p {
            font-size: 16px;
            line-height: 24px;
            color: #536387;
            margin-bottom: 22px;
            width: 75%;
        }
        .formbold-form-confirm > div {
            display: flex;
            gap: 15px;
        }

        .formbold-confirm-btn {
            display: flex;
            align-items: center;
            gap: 10px;
            background: #FFFFFF;
            border: 0.5px solid #DDE3EC;
            border-radius: 5px;
            font-size: 16px;
            line-height: 24px;
            color: #536387;
            cursor: pointer;
            padding: 10px 20px;
            transition: all .3s ease-in-out;
        }
        .formbold-confirm-btn {
            box-shadow: 0px 1px 2px rgba(0, 0, 0, 0.12);
        }
        .formbold-confirm-btn.active {
            background: #6A64F1;
            color: #FFFFFF;
        }

        .formbold-form-step-1,
        .formbold-form-step-2,
        .formbold-form-step-3 {
            display: none;
        }
        .formbold-form-step-1.active,
        .formbold-form-step-2.active,
        .formbold-form-step-3.active {
            display: block;
        }

        .formbold-form-btn-wrapper {
            display: flex;
            align-items: center;
            justify-content: flex-end;
            gap: 25px;
            margin-top: 25px;
        }
        .formbold-back-btn {
            cursor: pointer;
            background: #FFFFFF;
            border: none;
            color: #07074D;
            font-weight: 500;
            font-size: 16px;
            line-height: 24px;
            display: none;
        }
        .formbold-back-btn.active {
            display: block;
        }
        .formbold-btn {
            display: flex;
            align-items: center;
            gap: 5px;
            font-size: 16px;
            border-radius: 5px;
            padding: 10px 25px;
            border: none;
            font-weight: 500;
            background-color: #6A64F1;
            color: white;
            cursor: pointer;
        }
        .formbold-btn:hover {
            box-shadow: 0px 3px 8px rgba(0, 0, 0, 0.05);
        }
    </style>
{% endblock %}